[package]
name = "pallet-tx-fee-pot"
version = "0.0.1"
description = "Maintains a tx fee pot for validator payouts"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
frame-support = { workspace = true }
frame-system = { workspace = true }
codec = { workspace = true }
scale-info = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

pallet-assets-ext = { workspace = true }
pallet-balances = { workspace = true }
pallet-staking = { workspace = true }
seed-pallet-common = { workspace = true }
seed-primitives = { workspace = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"scale-info/std",
 	"frame-support/std",
	"frame-system/std",
	"pallet-balances/std",
	"pallet-staking/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"pallet-assets-ext/std",
	"seed-pallet-common/std",
	"seed-primitives/std",
]
try-runtime = ["frame-support/try-runtime"]
