[package]
name = "seed-client"
version = "0.0.1"
authors = ["Centrality Developers <support@centrality.ai>"]
edition = "2021"
publish = false
repository = "https://github.com/futureversecom/seed-network"
build = "build.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "seed-node"
path = "src/main.rs"

[dependencies]
futures = "0.3.21"
# TODO: remove after substrate update w https://github.com/paritytech/substrate/pull/11707
syn = "=1.0.97"
clap = { version = "3.1.18", features = ["derive"] }

sc-cli = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", features = ["wasmtime"] }
sp-core = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23" }
sc-network = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23" }
sc-executor = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", features = ["wasmtime"] }
sc-service = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", features = ["wasmtime"] }
sc-telemetry = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23" }
sc-keystore = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23" }
sc-transaction-pool = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23" }
sc-transaction-pool-api = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23" }
sc-consensus-aura = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23" }
sp-consensus-aura = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23" }
sp-consensus = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23" }
sc-consensus = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23" }
sc-finality-grandpa = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23" }
sp-finality-grandpa = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23" }
sc-client-api = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23" }
sp-runtime = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23" }
sp-timestamp = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23" }
sp-inherents = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23" }
sp-keyring = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23" }
frame-system = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23" }
pallet-transaction-payment = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }

# Frontier
fc-cli = { git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.23" }
fc-consensus = { git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.23" }
fc-db = { git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.23" }
fc-mapping-sync = { git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.23" }
fc-rpc = { git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.23" }
fc-rpc-core = { git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.23" }
fp-consensus = { git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.23" }
fp-dynamic-fee = { git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.23" }
fp-evm = { git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.23" }
fp-rpc = { git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.23" }
fp-storage = { git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.23" }

# These dependencies are used for the node template's RPCs
jsonrpsee = { version = "0.13.0", features = ["server"] }
sc-rpc = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23" }
sp-api = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23" }
sc-rpc-api = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23" }
sp-blockchain = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23" }
sp-block-builder = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23" }
sc-basic-authorship = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23" }
substrate-frame-rpc-system = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23" }
pallet-transaction-payment-rpc = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23" }

# These dependencies are used for runtime benchmarking
frame-benchmarking = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", optional = true }
frame-benchmarking-cli = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", optional = true }

# Local Dependencies
seed-primitives = { path = "../primitives" }
seed-runtime = { path = "../runtime" }

# CLI-specific dependencies
try-runtime-cli = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", optional = true }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23" }

[features]
default = []
runtime-benchmarks = ["frame-benchmarking", "frame-benchmarking-cli"]
# Enable features that allow the runtime to be tried and debugged. Name might be subject to change
# in the near future.
try-runtime = ["seed-runtime/try-runtime", "try-runtime-cli"]
