[package]
name = "seed-client"
version = "2.0.0"
authors = ["The Root Network Team"]
edition = "2021"
publish = false
repository = "https://github.com/futureversecom/seed"
build = "build.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
path = "src/lib.rs"

[[bin]]
name = "seed"
path = "src/main.rs"

[dependencies]
futures = "0.3.25"
clap = { version = "3.2.22", features = ["derive"] }
url = "2.3.1"
hex-literal = "0.3.4"

sc-cli = { git = "https://github.com/futureversecom/substrate", features = ["wasmtime"] , branch = "trn-tx-fees-trait" }
sp-core = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
sc-network = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
sc-executor = { git = "https://github.com/futureversecom/substrate", features = ["wasmtime"] , branch = "trn-tx-fees-trait" }
sc-service = { git = "https://github.com/futureversecom/substrate", features = ["wasmtime"] , branch = "trn-tx-fees-trait" }
sc-telemetry = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
sc-keystore = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
sc-transaction-pool = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
sc-transaction-pool-api = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
sc-consensus-babe = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
sc-consensus-babe-rpc = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
sc-consensus-uncles = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
sp-authorship = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
sp-consensus-babe = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
sp-consensus = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
sc-consensus = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
sc-consensus-epochs = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
sc-finality-grandpa = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
sc-finality-grandpa-rpc = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
sp-finality-grandpa = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
sc-client-api = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
sp-runtime = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
sp-timestamp = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
sp-inherents = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
sp-keyring = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
sp-keystore = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
sp-transaction-storage-proof = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
frame-system = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
pallet-transaction-payment = { git = "https://github.com/futureversecom/substrate" , branch = "trn-tx-fees-trait" }

# Frontier
fc-consensus = { default-features = false, git = "https://github.com/futureversecom/frontier", branch = "trn-tx-fees-trait" }
fc-db = { default-features = false, git = "https://github.com/futureversecom/frontier", branch = "trn-tx-fees-trait" }
fc-mapping-sync = { default-features = false, git = "https://github.com/futureversecom/frontier", branch = "trn-tx-fees-trait" }
fc-rpc = { default-features = false, git = "https://github.com/futureversecom/frontier", branch = "trn-tx-fees-trait", features = [ "rpc_binary_search_estimate" ] }
fc-rpc-core = { default-features = false, git = "https://github.com/futureversecom/frontier", branch = "trn-tx-fees-trait" }
fp-consensus = { default-features = false, git = "https://github.com/futureversecom/frontier", branch = "trn-tx-fees-trait" }
fp-rpc = { default-features = false, git = "https://github.com/futureversecom/frontier", branch = "trn-tx-fees-trait" }
fp-storage = { default-features = false, git = "https://github.com/futureversecom/frontier", branch = "trn-tx-fees-trait" }

# These dependencies are used for the node template's RPCs
jsonrpsee = { version = "0.14.0", features = ["server", "macros"] }
sc-rpc = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
sp-api = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
sc-rpc-api = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
sp-blockchain = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
sp-block-builder = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
sc-basic-authorship = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
substrate-frame-rpc-system = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }
pallet-transaction-payment-rpc = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }

# These dependencies are used for runtime benchmarking
frame-benchmarking = { git = "https://github.com/futureversecom/substrate", optional = true, branch = "trn-tx-fees-trait" }
frame-benchmarking-cli = { git = "https://github.com/futureversecom/substrate", optional = true, branch = "trn-tx-fees-trait" }

# Local Dependencies
ethy-gadget = { path = "../ethy-gadget" }
ethy-gadget-rpc = { path = "../ethy-gadget/rpc" }
seed-primitives = { path = "../primitives" }
seed-runtime = { path = "../runtime" }
pallet-dex-rpc = { path = "../pallet/dex/rpc" }
pallet-nft-rpc = { path = "../pallet/nft/rpc" }

# Diagnostics
log = "0.4.0"

# Try Runtime
frame-try-runtime = { git = "https://github.com/futureversecom/substrate", optional = true, branch = "trn-tx-fees-trait" }
try-runtime-cli = { git = "https://github.com/futureversecom/substrate", optional = true, branch = "trn-tx-fees-trait" }

# CLI-specific dependencies

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait" }

[features]
default = []
runtime-benchmarks = ["frame-benchmarking", "frame-benchmarking-cli", "seed-runtime/runtime-benchmarks"]
# Enable features that allow the runtime to be tried and debugged. Name might be subject to change
# in the near future.
try-runtime = ["seed-runtime/try-runtime", "try-runtime-cli"]
