[package]
name = "pallet-liquidity-pools"
version = "1.0.0"
authors = ["The Root Network Team"]
edition = "2021"
license = "GPL-3.0"
repository = "https://github.com/futureversecom/seed"
description = "Root Network Liquidity Pools pallet"

[dependencies]
codec = { workspace = true }
scale-info = { workspace = true }
sp-io = { workspace = true }
sp-std = { workspace = true }
sp-runtime = { workspace = true }
sp-arithmetic = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
frame-benchmarking = { workspace = true, optional = true }

seed-primitives = { workspace = true }

[dev-dependencies]
hex = { workspace = true }
hex-literal = { workspace = true }
sp-core = { workspace = true }
seed-pallet-common = { workspace = true }
pallet-assets = { workspace = true }
pallet-assets-ext = { workspace = true }
pallet-balances = { workspace = true }

[features]
default = ["std"]
std = [
    "codec/std",
    "scale-info/std",
    "sp-io/std",
    "sp-std/std",
    "sp-runtime/std",
    "sp-arithmetic/std",
    "frame-support/std",
    "frame-system/std",
    "frame-benchmarking?/std",
    "seed-primitives/std",
    "pallet-assets-ext/std",
]
runtime-benchmarks = ["frame-benchmarking"]
try-runtime = ["frame-support/try-runtime"]
