[package]
name = "ethy-gadget"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>", "Centrality Devleopers <support@centrality.ai>"]
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
ethabi = { version = "17.1.0" }
futures = "0.3.25"
futures-timer = "3.0.1"
hex = "0.4"
log = "0.4"
parking_lot = "0.12.1"
thiserror = "1.0"
codec = { version = "3.0.0", package = "parity-scale-codec", features = ["derive"] }
libsecp256k1 = { version = "0.6.0" }
prometheus = { package = "substrate-prometheus-endpoint", git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27-debug", version = "0.10.0-dev"}
sc-chain-spec = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27-debug" }
sc-client-api = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27-debug" }
sc-keystore = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27-debug" }
sc-network = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27-debug" }
sc-network-gossip = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27-debug" }
sc-utils = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27-debug" }
sp-api = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27-debug" }
sp-application-crypto = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27-debug" }
sp-arithmetic = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27-debug" }
sp-blockchain = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27-debug" }
sp-consensus = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27-debug" }
sp-core = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27-debug" }
sp-keystore = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27-debug" }
sp-runtime = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27-debug" }

seed-primitives = { path = "../primitives" }
xrpl-codec = { git = "https://github.com/futureversecom/xrpl-tx-codec", rev = "0.0.8" }

[dev-dependencies]
sc-network-test = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27-debug", version = "0.8.0" }
substrate-test-runtime-client = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27-debug" }
hex-literal = "*"
strum = { version = "0.24", features = ["derive"] }
