[package]
name = "pallet-staking"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME pallet staking"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.136", optional = true }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
	"derive",
] }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
sp-std = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
sp-io = { git = "https://github.com/futureversecom/substrate", default-features = false , branch = "polkadot-v0.9.27" }
sp-runtime = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
sp-staking = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
frame-support = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
frame-system = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
pallet-session = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false, features = ["historical"] }
pallet-authorship = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
sp-application-crypto = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
frame-election-provider-support = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
log = { version = "0.4.17", default-features = false }

# Optional imports for benchmarking
frame-benchmarking = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false, optional = true }
rand_chacha = { version = "0.2", default-features = false, optional = true }

[dev-dependencies]
sp-tracing =  { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27" }
sp-core =  { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27" }
sp-npos-elections = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27" }
pallet-balances =  { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27" }
pallet-timestamp =  { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27" }
pallet-staking-reward-curve =  { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27" }
pallet-bags-list = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", features = ["runtime-benchmarks"] }
substrate-test-utils =  { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27" }
frame-benchmarking = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27" }
rand_chacha = { version = "0.2" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"scale-info/std",
	"sp-std/std",
	"sp-io/std",
	"frame-support/std",
	"sp-runtime/std",
	"sp-staking/std",
	"pallet-session/std",
	"frame-system/std",
	"pallet-authorship/std",
	"sp-application-crypto/std",
	"log/std",
	"frame-election-provider-support/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-election-provider-support/runtime-benchmarks",
	"rand_chacha",
	"sp-staking/runtime-benchmarks"
]
try-runtime = ["frame-support/try-runtime"]
