version: '3'
services:
  bootnode:
    image: "ghcr.io/futureversecom/fork-release-state-${NETWORK:-root}"
    # image: zeeshans/seed:live-state-root
    command:
      - "/output/binary"
      - "--chain=/output/fork.json"
      - "--name=bootnode"
      - "--validator"
      - "--alice"
      - "--tmp"
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      - "--rpc-cors=all"
      - "--node-key=0000000000000000000000000000000000000000000000000000000000000001"
    deploy:
      resources:
        reservations:
          cpus: "0.1"
          memory: "512M"
        limits:
          cpus: "1"
          memory: "2512M"
    labels:
      # WS config
      # - "traefik.http.routers.bootnode-ws.rule=(Host(`localhost`) || Host(`devnet.cicd.rootnet.app`)) && PathPrefix(`/`)"
      - "traefik.http.routers.bootnode-ws.rule=Host(`devnet.cicd.rootnet.app`) && Path(`/`)"
      - "traefik.http.routers.bootnode-ws.entrypoints=substrate-ws"
      - "traefik.http.routers.bootnode-ws.service=node-ws-svc"
      - "traefik.http.services.node-ws-svc.loadbalancer.server.port=9944"
      - "traefik.http.middlewares.bootnode-ws.headers.customrequestheaders.Upgrade=websocket"
      - "traefik.http.middlewares.bootnode-ws.headers.customrequestheaders.Connection=Upgrade"
      - "traefik.http.routers.bootnode-ws.tls=true"
      - "traefik.http.routers.bootnode-ws.tls.certresolver=myresolver"
      # HTTP config
      # - "traefik.http.routers.bootnode-http.rule=(Host(`localhost`) || Host(`devnet.cicd.rootnet.app`)) && Path(`/http`)"
      - "traefik.http.routers.bootnode-http.rule=Host(`devnet.cicd.rootnet.app`) && Path(`/`)"
      - "traefik.http.routers.bootnode-http.entrypoints=substrate-http"
      - "traefik.http.routers.bootnode-http.service=bootnode-http-svc"
      - "traefik.http.services.bootnode-http-svc.loadbalancer.server.port=9933"
      - "traefik.http.routers.bootnode-http.tls=true"
      - "traefik.http.routers.bootnode-http.tls.certresolver=myresolver"

  validator1:
    image: "ghcr.io/futureversecom/fork-release-state-${NETWORK:-root}"
    # image: zeeshans/seed:live-state-root
    command:
      - "/output/binary"
      - "--chain=/output/fork.json"
      - "--name=validator1"
      - "--validator"
      - "--bob"
      - "--tmp"
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      - "--rpc-cors=all"
      - "--bootnodes=/dns/bootnode/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
    deploy:
      resources:
        reservations:
          cpus: "0.1"
          memory: "512M"
        limits:
          cpus: "1"
          memory: "2512M"
    depends_on:
      - bootnode
    labels:
      # WS config
      # - "traefik.http.routers.validator-1-ws.rule=(Host(`localhost`) || Host(`devnet.cicd.rootnet.app`)) && PathPrefix(`/`)"
      - "traefik.http.routers.validator-1-ws.rule=Host(`devnet.cicd.rootnet.app`) && Path(`/`)"
      - "traefik.http.routers.validator-1-ws.entrypoints=substrate-ws"
      - "traefik.http.routers.validator-1-ws.service=node-ws-svc"
      - "traefik.http.services.node-ws-svc.loadbalancer.server.port=9944"
      - "traefik.http.middlewares.validator-1-ws.headers.customrequestheaders.Upgrade=websocket"
      - "traefik.http.middlewares.validator-1-ws.headers.customrequestheaders.Connection=Upgrade"
      - "traefik.http.routers.validator-1-ws.tls=true"
      - "traefik.http.routers.validator-1-ws.tls.certresolver=myresolver"
      # HTTP config
      # - "traefik.http.routers.validator-1-http.rule=(Host(`localhost`) || Host(`devnet.cicd.rootnet.app`)) && Path(`/http`)"
      - "traefik.http.routers.validator-1-http.rule=Host(`devnet.cicd.rootnet.app`) && Path(`/`)"
      - "traefik.http.routers.validator-1-http.entrypoints=substrate-http"
      - "traefik.http.routers.validator-1-http.service=node-http-svc"
      - "traefik.http.services.node-http-svc.loadbalancer.server.port=9933"
      - "traefik.http.routers.validator-1-http.tls=true"
      - "traefik.http.routers.validator-1-http.tls.certresolver=myresolver"
  
  validator2:
    image: "ghcr.io/futureversecom/fork-release-state-${NETWORK:-root}"
    # image: zeeshans/seed:live-state-root
    command:
      - "/output/binary"
      - "--chain=/output/fork.json"
      - "--name=validator2"
      - "--validator"
      - "--charlie"
      - "--tmp"
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      - "--rpc-cors=all"
      - "--bootnodes=/dns/bootnode/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
    deploy:
      resources:
        reservations:
          cpus: "0.1"
          memory: "512M"
        limits:
          cpus: "1"
          memory: "2512M"
    depends_on:
      - bootnode
    labels:
      # WS config
      # - "traefik.http.routers.validator-2-ws.rule=(Host(`localhost`) || Host(`devnet.cicd.rootnet.app`)) && PathPrefix(`/`)"
      - "traefik.http.routers.validator-2-ws.rule=Host(`devnet.cicd.rootnet.app`) && Path(`/`)"
      - "traefik.http.routers.validator-2-ws.entrypoints=substrate-ws"
      - "traefik.http.routers.validator-2-ws.service=node-ws-svc"
      - "traefik.http.services.node-ws-svc.loadbalancer.server.port=9944"
      - "traefik.http.middlewares.validator-2-ws.headers.customrequestheaders.Upgrade=websocket"
      - "traefik.http.middlewares.validator-2-ws.headers.customrequestheaders.Connection=Upgrade"
      - "traefik.http.routers.validator-2-ws.tls=true"
      - "traefik.http.routers.validator-2-ws.tls.certresolver=myresolver"
      # HTTP config
      # - "traefik.http.routers.validator-2-http.rule=(Host(`localhost`) || Host(`devnet.cicd.rootnet.app`)) && Path(`/http`)"
      - "traefik.http.routers.validator-2-http.rule=Host(`devnet.cicd.rootnet.app`) && Path(`/`)"
      - "traefik.http.routers.validator-2-http.entrypoints=substrate-http"
      - "traefik.http.routers.validator-2-http.service=node-http-svc"
      - "traefik.http.services.node-http-svc.loadbalancer.server.port=9933"
      - "traefik.http.routers.validator-2-http.tls=true"
      - "traefik.http.routers.validator-2-http.tls.certresolver=myresolver"

# network already exists - attach to existing traefik network
networks:
  default:
    external:
      name: "traefik_default"
