# two node local network (alice + bob validators)
version: '3'
services:
  validator-0:
    image: ghcr.io/futureversecom/root-network:0.0.1-rc0
    volumes:
    - ./data/validator-0:/mnt/data
    - ./chain-spec:/mnt/chain-spec/:ro
    command:
      - --alice
      - --validator
      - --chain=dev
      - --base-path=/mnt/data
      - --name=validator-0
      - --unsafe-ws-external
      - --unsafe-rpc-external
      - --rpc-cors=all
    ports:
      - "9933:9933"
      - "9944:9944"
      - "30333:30333"
  validator-1:
    image: ghcr.io/futureversecom/root-network:0.0.1-rc0
    volumes:
    - ./data/validator-1:/mnt/data
    - ./chain-spec:/mnt/chain-spec/:ro
    command:
      - --bob
      - --validator
      - --chain=dev
      - --base-path=/mnt/data
      - --name=validator-1
