version: '3'
services:
  bootnode:
    image: "ghcr.io/futureversecom/fork-release-state-${NETWORK:-root}"
    pull_policy: always
    command: 
      - "/output/binary"
      - "--chain=/output/fork.json"
      - "--name=bootnode"
      - "--validator"
      - "--alice"
      - "--tmp"
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      - "--rpc-cors=all"
      - "--node-key=0000000000000000000000000000000000000000000000000000000000000001"

  validator1:
    image: "ghcr.io/futureversecom/fork-release-state-${NETWORK:-root}"
    pull_policy: always
    command: 
      - "/output/binary"
      - "--chain=/output/fork.json"
      - "--name=validator1"
      - "--validator"
      - "--bob"
      - "--tmp"
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      - "--rpc-cors=all"
      - "--bootnodes=/dns/bootnode/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
    depends_on:
      - bootnode
    ports:
      - 80:9944

  validator2:
    image: "ghcr.io/futureversecom/fork-release-state-${NETWORK:-root}"
    pull_policy: always
    command: 
      - "/output/binary"
      - "--chain=/output/fork.json"
      - "--name=validator2"
      - "--validator"
      - "--charlie"
      - "--tmp"
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      - "--rpc-cors=all"
      - "--bootnodes=/dns/bootnode/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
    depends_on:
      - bootnode
