version: "3"
services:
  root-validator:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./node-data:/node-data
    command:
      - --chain
      - root
      - --validator
      - -d
      - /node-data
      - --telemetry-url
      - "wss://telemetry.polkadot.io/submit/ 0"
      - --name
      - RootValidator
      - --sync
      - warp
    ports:
      - "9933:9933"
      - "9944:9944"
      - "30333:30333"
  root-validator-archive:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./node-data:/node-data
    command:
      - --chain
      - root
      - --validator
      - --pruning
      - archive
      - -d
      - /node-data
      - --telemetry-url
      - "wss://telemetry.polkadot.io/submit/ 0"
      - --name
      - RootValidator
    ports:
      - "9933:9933"
      - "9944:9944"
      - "30333:30333"
  porcini-validator:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./node-data:/node-data
    command:
      - --chain
      - porcini
      - --validator
      - -d
      - /node-data
      - --telemetry-url
      - "wss://telemetry.polkadot.io/submit/ 0"
      - --name
      - PorciniValidator
      - --sync
      - warp
    ports:
      - "9933:9933"
      - "9944:9944"
      - "30333:30333"
  porcini-validator-archive:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./node-data:/node-data
    command:
      - --chain
      - porcini
      - --validator
      - --pruning
      - archive
      - -d
      - /node-data
      - --telemetry-url
      - "wss://telemetry.polkadot.io/submit/ 0"
      - --name
      - PorciniValidator
    ports:
      - "9933:9933"
      - "9944:9944"
      - "30333:30333"
