[package]
name = "pallet-xrpl-transaction"
version = "1.0.0-dev"
authors = ["The Root Network Team"]
edition = "2021"
license = "GPL-3.0"
description = "XRPL Transaction Pallet"
repository = "https://github.com/futureversecom/trn-seed"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# Parity
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"], default-features = false }
scale-info = { version = "2.3.0", default-features = false, features = ["derive"] }

# Substrate FRAME
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.30", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.30", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.30", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.30", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.30", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.30", default-features = false }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.30", default-features = false }

# Benchmarking
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.30", optional = true, default-features = false }

# Custom
log = "0.4"
hex = { version = "0.4.3", default-features = false }
sha2 = { version = "0.10", default-features = false }
libsecp256k1 = { version = "0.7", default-features = false, features = [ "hmac" ] }
serde = { version = "1.0.145", default-features= false, features = ["derive"] }
serde_json = { version = "1.0.87", default-features = false, features = ["alloc"] }
xrpl_types = { git = "https://github.com/futureversecom/xrpl-sdk-rust", branch = "nostd-support-legacy", default-features = false }
xrpl_binary_codec = { git = "https://github.com/futureversecom/xrpl-sdk-rust", branch = "nostd-support-legacy", default-features = false, features = ["json"] }
seed-pallet-common = { path = "../common", default-features = false }
seed-primitives = { path = "../../primitives", default-features = false }
precompile-utils = { path = "../../evm-precompiles/utils", default-features = false }

[dev-dependencies]
frame-executive = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.30" }
pallet-assets = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.30" }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.30" }
fp-self-contained = { git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.30-trn-sp" }
seed-pallet-common= { path = "../common" }
pallet-assets-ext = { path = "../assets-ext" }
pallet-fee-control = { path = "../fee-control" }

[features]
default = ["std"]
std = [
	# Parity
	"codec/std",
	"scale-info/std",
	# Substrate FRAME
	"frame-support/std",
	"frame-system/std",
	"sp-core/std",
	"sp-std/std",
	"sp-runtime/std",
	"pallet-transaction-payment/std",
	# Custom
	"hex/std",
	"libsecp256k1/std",
	"serde/std",
	"serde_json/std",
	"seed-pallet-common/std",
	"seed-primitives/std",
	"precompile-utils/std",
]
try-runtime = ["frame-support/try-runtime"]
runtime-benchmarks = ["frame-benchmarking"]
