[package]
name = "pallet-partner-attribution"
version = "1.0.0-dev"
description = "Partner attribution pallet"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true }
scale-info = { workspace = true }

frame-support = { workspace = true }
frame-system = { workspace = true }
sp-core = { workspace = true }
sp-std = { workspace = true }
seed-primitives = { workspace = true }
frame-benchmarking = { workspace = true, optional = true }
precompile-utils = { workspace = true, optional = true }
seed-pallet-common = { workspace = true }

[dev-dependencies]
sp-core = { workspace = true }
sp-io = { workspace = true }
pallet-assets = { workspace = true }
pallet-balances = { workspace = true }
pallet-assets-ext = { workspace = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"scale-info/std",
	"frame-support/std",
	"frame-system/std",
	"sp-core/std",
	"sp-std/std",
	"seed-primitives/std",
	"seed-pallet-common/std",
	"pallet-assets-ext/std",
	"frame-benchmarking?/std",
]
try-runtime = ["frame-support/try-runtime"]
runtime-benchmarks = ["frame-benchmarking", "frame-support/runtime-benchmarks", "frame-system/runtime-benchmarks", "precompile-utils"]
