[package]
name = "seed-runtime"
version = "0.1.0"
authors = ["Centrality Developers <support@centrality.ai>"]
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
log = { version = "0.4.17", default-features = false }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
serde = { version = "1.0.143", optional = true, features = ["derive"] }

# Substrate
frame-executive = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }
frame-support = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }
frame-system = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }
frame-system-rpc-runtime-api = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }
frame-try-runtime = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false, optional = true }
pallet-aura = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }
pallet-assets = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }
pallet-authorship = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }
pallet-balances = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }
pallet-grandpa = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }
pallet-session = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }
pallet-sudo = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }
pallet-timestamp = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }
pallet-transaction-payment = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }
sp-api = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }
sp-block-builder = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }
sp-consensus-aura = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }
sp-core = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }
sp-inherents = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }
sp-io = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }
sp-offchain = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }
sp-runtime = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }
sp-session = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }
sp-std = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }
sp-transaction-pool = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }
sp-version = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }

# EVM support
fp-rpc = { default-features = false, git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.23" }
fp-self-contained = { default-features = false, git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.23" }
pallet-base-fee = { default-features = false, git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.23" }
pallet-ethereum = { default-features = false, git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.23" }
pallet-evm = { default-features = false, git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.23" }
pallet-evm-precompile-blake2 = { default-features = false, git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.23" }
pallet-evm-precompile-modexp = { default-features = false, git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.23" }
pallet-evm-precompile-simple = { default-features = false, git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.23" }
pallet-evm-precompile-sha3fips = { default-features = false, git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.23" }
precompile-utils = { path = "../evm-precompiles/utils", default-features = false }
rustc-hex = { version = "2.1.0", default-features = false }

pallet-assets-ext = { path = "../pallet/assets-ext", default-features = false }
pallet-dex = { path = "../pallet/dex", default-features = false }
pallet-nft = { path = "../pallet/nft", default-features = false }

seed-primitives = { path = "../primitives", default-features = false }

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"log/std",
	"scale-info/std",
	"serde",
	"frame-executive/std",
	"frame-support/std",
	"frame-system/std",
	"frame-system-rpc-runtime-api/std",
	"pallet-authorship/std",
	"pallet-aura/std",
	"pallet-assets/std",
	"pallet-balances/std",
	"pallet-grandpa/std",
	"pallet-session/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-aura/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"pallet-assets-ext/std",
	"pallet-dex/std",
	"pallet-nft/std",
	"seed-primitives/std",
	"fp-rpc/std",
	"fp-self-contained/std",
	"pallet-base-fee/std",
	"pallet-ethereum/std",
	"pallet-evm/std",
	"pallet-evm-precompile-blake2/std",
	"pallet-evm-precompile-modexp/std",
	"pallet-evm-precompile-simple/std",
	"pallet-evm-precompile-sha3fips/std",
	"precompile-utils/std",
	"rustc-hex/std",
]
try-runtime = [
	"frame-executive/try-runtime",
	"frame-try-runtime",
]
