[package]
name = "seed-runtime"
version = "0.1.0"
authors = ["Centrality Developers <support@centrality.ai>"]
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
log = { version = "0.4.17", default-features = false }
scale-info = { version = "2.2.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.144", default-features = false, optional = true, features = ["derive"] }

# Substrate
frame-executive = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
frame-election-provider-support = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
frame-support = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
frame-system = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
frame-system-rpc-runtime-api = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
frame-try-runtime = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false, optional = true }
pallet-assets = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
pallet-authorship = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
pallet-babe = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
pallet-balances = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
pallet-bags-list = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
pallet-election-provider-multi-phase = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
pallet-grandpa = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
pallet-im-online = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
pallet-nomination-pools = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
pallet-offences = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
pallet-session = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
pallet-staking = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
pallet-sudo = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
pallet-timestamp = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
pallet-transaction-payment = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
sp-api = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
sp-block-builder = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
sp-consensus-babe = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
sp-core = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
sp-npos-elections = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
sp-inherents = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
sp-io = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
sp-offchain = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
sp-runtime = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
sp-session = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
sp-staking = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
sp-std = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
sp-transaction-pool = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
sp-version = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }

# EVM support
fp-rpc = { default-features = false, git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.27" }
fp-self-contained = { default-features = false, git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.27" }
hex-literal = { version = "0.3.4", default-features = false }
pallet-base-fee = { default-features = false, git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.27" }
pallet-ethereum = { default-features = false, git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.27" }
pallet-evm = { default-features = false, git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.27" }
pallet-evm-precompile-blake2 = { default-features = false, git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.27" }
pallet-evm-precompile-modexp = { default-features = false, git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.27" }
pallet-evm-precompile-simple = { default-features = false, git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.27" }
pallet-evm-precompile-sha3fips = { default-features = false, git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.27" }
precompile-utils = { path = "../evm-precompiles/utils", default-features = false }
pallet-evm-precompiles-erc721 = { path = "../evm-precompiles/erc721", default-features = false }
pallet-evm-precompiles-erc20 = { path = "../evm-precompiles/erc20", default-features = false }
rustc-hex = { version = "2.1.0", default-features = false }

pallet-assets-ext = { path = "../pallet/assets-ext", default-features = false }
pallet-dex = { path = "../pallet/dex", default-features = false }
pallet-echo = { path = "../pallet/echo", default-features = false }
pallet-ethy = { path = "../pallet/ethy", default-features = false }
pallet-nft = { path = "../pallet/nft", default-features = false }
pallet-token-approvals = { path = "../pallet/token-approvals", default-features = false }
pallet-tx-fee-pot = { path = "../pallet/tx-fee-pot", default-features = false }
pallet-xrpl-bridge = { path = "../pallet/xrpl-bridge", default-features = false }

seed-pallet-common = { path = "../pallet/common", default-features = false }
seed-primitives = { path = "../primitives", default-features = false }

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27" }

[dev-dependencies]
seed-client = { path = "../client" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"log/std",
	"scale-info/std",
	"serde",
	"frame-executive/std",
	"frame-election-provider-support/std",
	"frame-support/std",
	"frame-system/std",
	"frame-system-rpc-runtime-api/std",
	"pallet-authorship/std",
	"pallet-assets/std",
	"pallet-babe/std",
	"pallet-bags-list/std",
	"pallet-balances/std",
	"pallet-echo/std",
	"pallet-election-provider-multi-phase/std",
	"pallet-grandpa/std",
	"pallet-im-online/std",
	"pallet-nomination-pools/std",
	"pallet-offences/std",
	"pallet-session/std",
	"pallet-staking/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-babe/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-npos-elections/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-staking/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"pallet-assets-ext/std",
	"pallet-dex/std",
	"pallet-ethy/std",
	"pallet-nft/std",
	"pallet-xrpl-bridge/std",
	"pallet-tx-fee-pot/std",
	"pallet-token-approvals/std",
	"seed-primitives/std",
	"fp-rpc/std",
	"fp-self-contained/std",
	"pallet-base-fee/std",
	"pallet-ethereum/std",
	"pallet-evm/std",
	"pallet-evm-precompile-blake2/std",
	"pallet-evm-precompile-modexp/std",
	"pallet-evm-precompile-simple/std",
	"pallet-evm-precompile-sha3fips/std",
	"pallet-evm-precompiles-erc721/std",
	"pallet-evm-precompiles-erc20/std",
	"precompile-utils/std",
	"rustc-hex/std",
]
try-runtime = [
	"frame-executive/try-runtime",
	"frame-try-runtime",
]
