[package]
authors.workspace = true
edition.workspace = true
name = "pallet-catalyst-runtime-api"
version = "0.0.1"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-api = { workspace = true }
sp-runtime = { workspace = true }

[features]
default = ["std"]
std = ["sp-api/std", "sp-runtime/std"]
