// This file is part of Substrate.

// Copyright (C) 2022 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_sylo_action_permissions
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2025-06-08, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `Johns-Macbook-Pro.local`, CPU: `<UNKNOWN>`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/seed
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=pallet-sylo-action-permissions
// --extrinsic=*
// --wasm-execution=compiled
// --heap-pages=4096
// --output
// ./pallet/sylo-action-permissions/src/weights.rs
// --template
// ./scripts/pallet_template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_sylo_action_permissions.
pub trait WeightInfo {
	fn grant_dispatch_permission(c: u32, ) -> Weight;
	fn update_dispatch_permission(c: u32, ) -> Weight;
	fn revoke_dispatch_permission() -> Weight;
	fn transact() -> Weight;
}

/// Weights for pallet_sylo_action_permissions using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: `SyloActionPermissions::DispatchPermissions` (r:1 w:1)
	// Proof: `SyloActionPermissions::DispatchPermissions` (`max_values`: None, `max_size`: Some(1004101), added: 1006576, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 1000]`.
	fn grant_dispatch_permission(c: u32, ) -> Weight {
		Weight::from_all(14_031_493)
			// Standard Error: 3_014
			.saturating_add(Weight::from_all(1_035_865_u64).saturating_mul(c as u64))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// Storage: `SyloActionPermissions::DispatchPermissions` (r:1 w:1)
	// Proof: `SyloActionPermissions::DispatchPermissions` (`max_values`: None, `max_size`: Some(1004101), added: 1006576, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 1000]`.
	fn update_dispatch_permission(c: u32, ) -> Weight {
		Weight::from_all(18_017_737)
			// Standard Error: 2_268
			.saturating_add(Weight::from_all(733_136_u64).saturating_mul(c as u64))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// Storage: `SyloActionPermissions::DispatchPermissions` (r:1 w:1)
	// Proof: `SyloActionPermissions::DispatchPermissions` (`max_values`: None, `max_size`: Some(1004101), added: 1006576, mode: `MaxEncodedLen`)
	fn revoke_dispatch_permission() -> Weight {
		Weight::from_all(15_000_000)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// Storage: `SyloActionPermissions::DispatchPermissions` (r:1 w:0)
	// Proof: `SyloActionPermissions::DispatchPermissions` (`max_values`: None, `max_size`: Some(1004101), added: 1006576, mode: `MaxEncodedLen`)
	// Storage: `MaintenanceMode::BlockedCalls` (r:1 w:0)
	// Proof: `MaintenanceMode::BlockedCalls` (`max_values`: None, `max_size`: Some(111), added: 2586, mode: `MaxEncodedLen`)
	// Storage: `MaintenanceMode::BlockedPallets` (r:1 w:0)
	// Proof: `MaintenanceMode::BlockedPallets` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	fn transact() -> Weight {
		Weight::from_all(24_000_000)
			.saturating_add(T::DbWeight::get().reads(3))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: `SyloActionPermissions::DispatchPermissions` (r:1 w:1)
	// Proof: `SyloActionPermissions::DispatchPermissions` (`max_values`: None, `max_size`: Some(1004101), added: 1006576, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 1000]`.
	fn grant_dispatch_permission(c: u32, ) -> Weight {
		Weight::from_all(14_031_493)
			// Standard Error: 3_014
			.saturating_add(Weight::from_all(1_035_865_u64).saturating_mul(c as u64))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	// Storage: `SyloActionPermissions::DispatchPermissions` (r:1 w:1)
	// Proof: `SyloActionPermissions::DispatchPermissions` (`max_values`: None, `max_size`: Some(1004101), added: 1006576, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 1000]`.
	fn update_dispatch_permission(c: u32, ) -> Weight {
		Weight::from_all(18_017_737)
			// Standard Error: 2_268
			.saturating_add(Weight::from_all(733_136_u64).saturating_mul(c as u64))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	// Storage: `SyloActionPermissions::DispatchPermissions` (r:1 w:1)
	// Proof: `SyloActionPermissions::DispatchPermissions` (`max_values`: None, `max_size`: Some(1004101), added: 1006576, mode: `MaxEncodedLen`)
	fn revoke_dispatch_permission() -> Weight {
		Weight::from_all(15_000_000)
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	// Storage: `SyloActionPermissions::DispatchPermissions` (r:1 w:0)
	// Proof: `SyloActionPermissions::DispatchPermissions` (`max_values`: None, `max_size`: Some(1004101), added: 1006576, mode: `MaxEncodedLen`)
	// Storage: `MaintenanceMode::BlockedCalls` (r:1 w:0)
	// Proof: `MaintenanceMode::BlockedCalls` (`max_values`: None, `max_size`: Some(111), added: 2586, mode: `MaxEncodedLen`)
	// Storage: `MaintenanceMode::BlockedPallets` (r:1 w:0)
	// Proof: `MaintenanceMode::BlockedPallets` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	fn transact() -> Weight {
		Weight::from_all(24_000_000)
			.saturating_add(RocksDbWeight::get().reads(3))
	}
}

