[package]
name = "pallet-nft-rpc-runtime-api"
version = "2.2.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
codec = { workspace = true }
sp-api = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
pallet-nft = { workspace = true }
seed-primitives = { workspace = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-api/std",
	"codec/std",
	"sp-runtime/std",
	"sp-std/std",
	"pallet-nft/std",
	"codec/std",
	"seed-primitives/std",
]
