[package]
authors = ["Centrality Developers <support@centrality.ai>"]
edition = '2021'
name    = 'pallet-xrpl-bridge'
version = '1.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec              = { package = 'parity-scale-codec', version = '3.0.0', default-features = false }
frame-benchmarking = { git = 'https://github.com/futureversecom/substrate.git', branch = 'polkadot-v0.9.27', default-features = false, optional = true }
frame-support      = { git = 'https://github.com/futureversecom/substrate.git', branch = 'polkadot-v0.9.27', default-features = false }
frame-system       = { git = 'https://github.com/futureversecom/substrate.git', branch = 'polkadot-v0.9.27', default-features = false }
pallet-assets      = { git = 'https://github.com/futureversecom/substrate.git', branch = 'polkadot-v0.9.27', default-features = false }
pallet-balances    = { git = 'https://github.com/futureversecom/substrate.git', branch = 'polkadot-v0.9.27', default-features = false }
pallet-timestamp   = { git = 'https://github.com/futureversecom/substrate.git', branch = 'polkadot-v0.9.27', default-features = false }
scale-info         = { version = '2.1', default-features = false, features = ['derive'] }
serde              = { version = '1.0.136', features = ['derive'], optional = true }
sp-runtime         = { git = 'https://github.com/futureversecom/substrate.git', branch = 'polkadot-v0.9.27', default-features = false }
sp-std             = { git = 'https://github.com/futureversecom/substrate.git', branch = 'polkadot-v0.9.27', default-features = false }
seed-primitives                           = { path = "../../primitives", default-features = false }

[dev-dependencies]
sp-core                 = { git = 'https://github.com/futureversecom/substrate.git', branch = 'polkadot-v0.9.27' }
sp-io                   = { git = 'https://github.com/futureversecom/substrate.git', branch = 'polkadot-v0.9.27' }
sp-keystore             = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27" }


[features]
default            = ['std']
runtime-benchmarks = ['frame-benchmarking']
std                = [
  'serde',
  'codec/std',
  'sp-runtime/std',
  'frame-support/std',
  'frame-system/std',
  'sp-std/std',
  "seed-primitives/std",
  'scale-info/std',
  'frame-benchmarking/std',
  'pallet-assets/std',
  'pallet-balances/std',
  'pallet-assets/std',
  'pallet-timestamp/std',
]
try-runtime        = ['frame-support/try-runtime']

[lib]
doctest = false
