[package]
name = "pallet-xrpl-bridge"
version = "0.0.1"
description = "XRPL Bridge to process transactions"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
log = { workspace = true }
hex-literal = { workspace = true }
xrpl-codec = { workspace = true }

frame-benchmarking = { workspace = true, optional = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
codec = { workspace = true }
scale-info = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

pallet-assets = { workspace = true }
pallet-assets-ext = { workspace = true }
pallet-balances = { workspace = true }
pallet-timestamp = { workspace = true }
seed-primitives = { workspace = true }
seed-pallet-common = { workspace = true }

[dev-dependencies]
pallet-nft = { workspace = true }

[features]
default = ['std']
std = [
  'codec/std',
  'sp-runtime/std',
  'sp-core/std',
  'frame-support/std',
  'frame-system/std',
  'sp-std/std',
  "seed-primitives/std",
  'scale-info/std',
  'frame-benchmarking/std',
  'pallet-assets/std',
  'pallet-balances/std',
  'pallet-assets/std',
  'pallet-timestamp/std',
  "seed-pallet-common/std",
  "pallet-assets-ext/std",
  "pallet-nft/std",
  "log/std",
  "frame-benchmarking?/std",
]
runtime-benchmarks = ['frame-benchmarking', "seed-pallet-common/runtime-benchmarks"]
try-runtime = ['frame-support/try-runtime']

[lib]
doctest = false
