[package]
name = "pallet-xrpl-bridge"
version = "0.0.1"
authors = ["Centrality Developers <support@centrality.ai>"]
edition = "2021"
license = "GPL-3.0"
repository = "https://github.com/futureversecom/seed-network"
description = "XRPL Bridge to process transactions"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec              = { package = 'parity-scale-codec', version = '3.0.0', default-features = false }
frame-benchmarking = { git = 'https://github.com/futureversecom/substrate.git', branch = 'polkadot-v0.9.27', default-features = false, optional = true }
frame-support      = { git = 'https://github.com/futureversecom/substrate.git', branch = 'polkadot-v0.9.27', default-features = false }
frame-system       = { git = 'https://github.com/futureversecom/substrate.git', branch = 'polkadot-v0.9.27', default-features = false }
pallet-assets      = { git = 'https://github.com/futureversecom/substrate.git', branch = 'polkadot-v0.9.27', default-features = false }
pallet-balances    = { git = 'https://github.com/futureversecom/substrate.git', branch = 'polkadot-v0.9.27', default-features = false }
pallet-timestamp   = { git = 'https://github.com/futureversecom/substrate.git', branch = 'polkadot-v0.9.27', default-features = false }
scale-info         = { version = '2.2.0', default-features = false, features = ['derive'] }
serde              = { version = '1.0.144', features = ['derive'], optional = true }
sp-runtime         = { git = 'https://github.com/futureversecom/substrate.git', branch = 'polkadot-v0.9.27', default-features = false }
sp-std             = { git = 'https://github.com/futureversecom/substrate.git', branch = 'polkadot-v0.9.27', default-features = false }
sp-core            = { git = 'https://github.com/futureversecom/substrate.git', branch = 'polkadot-v0.9.27', default-features = false }

seed-primitives    = { path = "../../primitives", default-features = false }
seed-pallet-common = { path = "../common", default-features = false }
pallet-assets-ext = { path = "../../pallet/assets-ext", default-features = false }

[dev-dependencies]
sp-io                   = { git = 'https://github.com/futureversecom/substrate.git', branch = 'polkadot-v0.9.27' }
sp-keystore             = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27" }


[features]
default            = ['std']
runtime-benchmarks = ['frame-benchmarking']
std                = [
  'serde',
  'codec/std',
  'sp-runtime/std',
  'sp-core/std',
  'frame-support/std',
  'frame-system/std',
  'sp-std/std',
  "seed-primitives/std",
  'scale-info/std',
  'frame-benchmarking/std',
  'pallet-assets/std',
  'pallet-balances/std',
  'pallet-assets/std',
  'pallet-timestamp/std',
  "seed-pallet-common/std",
  "pallet-assets-ext/std",
]
try-runtime        = ['frame-support/try-runtime']

[lib]
doctest = false
