[package]
name = "pallet-staking-payouts"
version = "1.0.0"
authors = ["The Root Network Team"]
edition = "2021"
license = "GPL-3.0"
repository = "https://github.com/futureversecom/seed"
description = "Root Network Staking payouts pallet"

[dependencies]
seed-primitives = { path = "../../primitives", default-features = false }
seed-pallet-common = { path = "../common", default-features = false }

codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }

# Substrate primitives
sp-core = { git = "https://github.com/futureversecom/substrate", default-features = false, branch = "polkadot-v0.9.27" }
sp-std = { git = "https://github.com/futureversecom/substrate", default-features = false, branch = "polkadot-v0.9.27" }
sp-staking = { git = "https://github.com/futureversecom/substrate", default-features = false, branch = "polkadot-v0.9.27" }
sp-runtime = { git = "https://github.com/futureversecom/substrate", default-features = false, branch = "polkadot-v0.9.27" }

frame-support = { git = "https://github.com/futureversecom/substrate", default-features = false, branch = "polkadot-v0.9.27" }
frame-system = { git = "https://github.com/futureversecom/substrate", default-features = false, branch = "polkadot-v0.9.27" }
frame-benchmarking = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", optional = true, default-features = false }
scale-info = { version = "2.3.0", default-features = false, features = ["derive"] }
pallet-staking = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27",default-features = false }
# frame-election-support-provider = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27",default-features = false }
frame-election-provider-support  = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27",default-features = false }
log = "0.4.0"

[dev-dependencies]
sp-io = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27" }
sp-staking = { git = "https://github.com/futureversecom/substrate", default-features = false, branch = "polkadot-v0.9.27" }
pallet-assets-ext = { path = "../../pallet/assets-ext", default-features = false }
pallet-tx-fee-pot = { path = "../../pallet/tx-fee-pot", default-features = false }
pallet-balances = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
pallet-assets = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
pallet-session = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }
pallet-timestamp = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "scale-info/std",
    "seed-primitives/std",
    "seed-pallet-common/std",
    "sp-core/std",
    "sp-std/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-staking/std",
    "frame-election-provider-support/std",
    "sp-staking/std",
    "sp-runtime/std"
]
runtime-benchmarks = ["frame-benchmarking"]
try-runtime = ["frame-support/try-runtime"]