[package]
name    = 'pallet-validator-stake'
version = "0.0.1"
description = "A validator staking pallet for GIANT."
authors = ["GIANT DevHub <https://github.com/giant-protocol>"]
homepage = "https://github.com/giant-protocol/GIANT"
edition = "2021"
license = "GPLv3.0"
publish = false
repository = "https://github.com/giant-protocol/GIANT"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec                                     = { package = 'parity-scale-codec', version = '3.0.0', default-features = false }
frame-benchmarking                        = { git = 'https://github.com/futureversecom/substrate.git', default-features = false, optional = true , branch = "polkadot-v0.9.27" }
frame-support                             = { git = 'https://github.com/futureversecom/substrate.git', default-features = false , branch = "polkadot-v0.9.27" }
frame-system                              = { git = 'https://github.com/futureversecom/substrate.git', default-features = false , branch = "polkadot-v0.9.27" }
orml-traits                               = { git = 'https://github.com/futureversecom/open-runtime-module-library.git', default-features = false , branch = "polkadot-v0.9.27"}
pallet-balances                           = { git = 'https://github.com/futureversecom/substrate.git', default-features = false , branch = "polkadot-v0.9.27" }
pallet-timestamp                          = { git = 'https://github.com/futureversecom/substrate.git', default-features = false , branch = "polkadot-v0.9.27" }
scale-info                                = { version = '2.1.2', default-features = false, features = ['derive'] }
serde                                     = { version = '1.0.136', features = ['derive'], optional = true }
sp-arithmetic 							  = { git = 'https://github.com/futureversecom/substrate.git', default-features = false , branch = "polkadot-v0.9.27" }
sp-runtime                                = { git = 'https://github.com/futureversecom/substrate.git', default-features = false , branch = "polkadot-v0.9.27" }
sp-std                                    = { git = 'https://github.com/futureversecom/substrate.git', default-features = false , branch = "polkadot-v0.9.27" }
pallet-transaction-payment                = { git = "https://github.com/futureversecom/substrate.git", default-features = false, branch = "polkadot-v0.9.27" }
seed-primitives                           = { path = "../../primitives", default-features = false }
pallet-validator-set                      = { path = "../validator_set", default-features = false }

[dev-dependencies]
orml-oracle                               = { git = 'https://github.com/futureversecom/open-runtime-module-library.git', default-features = false , branch = "polkadot-v0.9.27" }
sp-core                                   = { git = 'https://github.com/futureversecom/substrate.git', branch = "polkadot-v0.9.27" }
sp-io 										                = { git = "https://github.com/futureversecom/substrate.git", default-features = false, branch = "polkadot-v0.9.27" }
sp-keystore                               = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.27" }


[features]
default            = ['std']
runtime-benchmarks = ['frame-benchmarking']
std                = [
  'codec/std',
  'frame-support/std',
  'frame-system/std',
  'frame-benchmarking/std',
  'orml-traits/std',
  'sp-runtime/std',
  'sp-std/std',
  "seed-primitives/std",
  'pallet-balances/std',
  'pallet-timestamp/std',
  'pallet-transaction-payment/std',
  'serde',
  'scale-info/std',
]
try-runtime        = ['frame-support/try-runtime']

[lib]
doctest = false
