version: "3"

services:
  seed:
    image: ghcr.io/futureversecom/seed:latest
    command:
      - --dev
      - --alice
      - --validator
      - --base-path=/mnt/data
      - --name=validator-0
      - --unsafe-rpc-external
      - --rpc-port=9944
      - --rpc-cors=all
    ports:
      - "9944:9944"
