[package]
name = "pallet-xrpl"
version = "1.0.0-dev"
description = "XRPL Pallet"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
hex = { workspace = true }
libsecp256k1 = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
xrpl_binary_codec = { git = "https://github.com/futureversecom/xrpl-sdk-rust", default-features = false, features = ["json"] }
xrpl_types = { git = "https://github.com/futureversecom/xrpl-sdk-rust", default-features = false }

frame-benchmarking = { workspace = true, optional = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
codec = { workspace = true }
scale-info = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-std = { workspace = true }
sp-runtime = { workspace = true }
pallet-transaction-payment = { workspace = true }

seed-pallet-common = { workspace = true }
seed-primitives = { workspace = true }
precompile-utils = { workspace = true }

[dev-dependencies]
frame-executive = { workspace = true }
pallet-assets = { workspace = true }
pallet-balances = { workspace = true }
fp-self-contained = { workspace = true, default-features = true }
seed-pallet-common= { workspace = true }
pallet-assets-ext = { workspace = true, default-features = true }
pallet-fee-control = { workspace = true }

[features]
default = ["std"]
std = [
	# Parity
	"codec/std",
	"scale-info/std",
	# Substrate FRAME
	"frame-support/std",
	"frame-system/std",
	"sp-core/std",
	"sp-std/std",
	"sp-runtime/std",
	"pallet-transaction-payment/std",
	# Custom
	"hex/std",
	"libsecp256k1/std",
	"serde/std",
	"serde_json/std",
	"seed-pallet-common/std",
	"seed-primitives/std",
	"precompile-utils/std",
	"frame-benchmarking?/std",
]
try-runtime = ["frame-support/try-runtime"]
runtime-benchmarks = ["frame-benchmarking"]
