[package]
name = "pallet-validator-set"
version = "0.0.1"
authors = ["Centrality Developers <support@centrality.ai>"]
edition = "2021"
license = "GPL-3.0"
repository = "https://github.com/futureversecom/seed"
description = "To add and remove validators"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
hex-literal = { version = "0.3.4", default-features = false }
rustc-hex = { version = "2.1.0", default-features = false }
async-trait = { version = "0.1.57", default-features = false }
tokio-tungstenite = { version = "0.17.2", features = ["native-tls"] }
futures = "0.3.21"
tokio = { version = "1.20.1", features = ["full"] }

codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", ] }
frame-support = { git = "https://github.com/futureversecom/substrate.git", branch = "polkadot-v0.9.27", default-features = false }
frame-system = {  git = "https://github.com/futureversecom/substrate.git", branch = "polkadot-v0.9.27", default-features = false }
scale-info = { version = "2.1.2", default-features = false, features = ["derive"] }
serde = { version = '1.0.137', features = ['derive'], optional = true, default-features = false }
sp-core = {  git = "https://github.com/futureversecom/substrate.git", branch = "polkadot-v0.9.27", default-features = false }
sp-io 	= { default-features = false, git = "https://github.com/futureversecom/substrate.git", branch = "polkadot-v0.9.27" }
sp-runtime = {  git = "https://github.com/futureversecom/substrate.git", branch = "polkadot-v0.9.27", default-features = false }
sp-std = {  git = "https://github.com/futureversecom/substrate.git", branch = "polkadot-v0.9.27", default-features = false }
sp-application-crypto = { git = "https://github.com/futureversecom/substrate", default-features = false, branch = "polkadot-v0.9.27" }
frame-benchmarking = { default-features = false, git = "https://github.com/futureversecom/substrate.git", branch = "polkadot-v0.9.27", optional = true }

xrpl-rust = { git = "https://github.com/futureversecom/xrpl-rust.git", default-features = false, features = ["core", "models"] }

seed-primitives                           = { path = "../../primitives", default-features = false }
seed-pallet-common = { path = "../common", default-features = false }
pallet-xrpl-bridge = { path = "../xrpl-bridge", default-features = false }

[features]
default = ['std']
std = [
    'codec/std',
    'sp-std/std',
    'sp-io/std',
    'serde',
    'sp-runtime/std',
    'frame-support/std',
    'sp-core/std',
    "sp-application-crypto/std",
    'frame-system/std',
    'frame-benchmarking/std',
    "seed-primitives/std",
    "seed-pallet-common/std",
    "pallet-xrpl-bridge/std",
]

runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks"]
try-runtime = ["frame-support/try-runtime"]
