[package]
name = "pallet-futurepass"
version = "1.0.0-dev"
description = "FuturePass"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
hex = { workspace = true }
hex-literal = { workspace = true }
codec = { workspace = true }
scale-info = { workspace = true }

# Substrate FRAME
frame-benchmarking = { workspace = true, optional = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-std = { workspace = true }
sp-runtime = { workspace = true }

precompile-utils = { workspace = true }
seed-pallet-common = { workspace = true }
seed-primitives = { workspace = true }

[dev-dependencies]
seed-runtime = { workspace = true, default-features = true }
pallet-balances = { workspace = true }
pallet-assets = { workspace = true }
pallet-proxy = { workspace = true }
pallet-assets-ext = { workspace = true }
pallet-fee-control = { workspace = true }
pallet-dex = { workspace = true }
pallet-nft = { workspace = true }
seed-pallet-common= { workspace = true, default-features = true }

[features]
default = ["std"]
std = [
	# Parity
	"hex/std",
	"codec/std",
	"scale-info/std",
	# Substrate FRAME
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"sp-core/std",
	"sp-std/std",
	"sp-runtime/std",
	# Custom
	"seed-pallet-common/std",
	"seed-primitives/std",
	"precompile-utils/std",
]
try-runtime = ["frame-support/try-runtime"]
runtime-benchmarks = ["frame-benchmarking", "seed-runtime/runtime-benchmarks"]
