name: "CI"

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - "main"

permissions: # GITHUB_TOKEN permissions
  contents: read
  packages: read

jobs:
  setup:
    runs-on: [linux]
    steps:
      - name: Cleanup # https://github.com/actions/checkout/issues/211#issuecomment-1300522915
        uses: AutoModality/action-clean@v1

      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.SEED_GHCR_PAT }}

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          node-version: "lts/*"
          cache: "yarn"

      # - name: "Install yarn globally"
      #   run: "npm install -g yarn"

      - name: "Install the dependencies"
        run: "yarn install --immutable --prefer-offline"

  # lint:
  #   needs: setup
  #   runs-on: [linux]
  #   steps:
      - name: "Format the code"
        run: "yarn format"

      - name: "Lint the code"
        run: "yarn lint:ts"

      - name: "Add lint summary"
        run: |
          echo "## Lint results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

  # test:
  #   needs: setup
  #   runs-on: [linux]
  #   steps:

      - name: "Pull latest seed image"
        run: "docker pull ghcr.io/futureversecom/seed:latest"

      - name: "Compile the contracts and generate the TypeChain bindings"
        run: "yarn hardhat compile"

      - name: "Test the contracts"
        run: "yarn test"

      # - name: "Test the contracts and generate the coverage report"
      #   run: "yarn coverage"

      # - name: "Add test summary"
      #   run: |
      #     echo "## Test results" >> $GITHUB_STEP_SUMMARY
