apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true

  - name: Alertmanager
    type: alertmanager
    url: http://alertmanager:9093
    access: proxy
