[package]
name = "seed-runtime-constants"
version = "0.9.28"
authors = ["The Root Network Team"]
edition = "2021"

[dependencies]
sp-runtime = { git = "https://github.com/futureversecom/trn-substrate", branch = "polkadot-v0.9.30", default-features = false }
sp-core = { git = "https://github.com/futureversecom/trn-substrate", branch = "polkadot-v0.9.30", default-features = false }
sp-weights = { git = "https://github.com/futureversecom/trn-substrate", branch = "polkadot-v0.9.30", default-features = false }

[features]
default = ["std"]
std = [
	"sp-runtime/std",
	"sp-core/std",
	"sp-weights/std",
]
