[package]
name = "seed-runtime-constants"
version = "0.9.28"
authors.workspace = true
edition.workspace = true

[dependencies]
sp-runtime = { workspace = true }
sp-core = { workspace = true }
sp-weights = { workspace = true }

[features]
default = ["std"]
std = [
	"sp-runtime/std",
	"sp-core/std",
	"sp-weights/std",
]
