[package]
name = "seed-runtime-constants"
version = "0.9.28"
authors = ["The Root Network Team"]
edition = "2021"

[dependencies]
frame-support = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait", default-features = false }
sp-runtime = { git = "https://github.com/futureversecom/substrate", branch = "trn-tx-fees-trait", default-features = false }

[features]
default = ["std"]
std = [
	"sp-runtime/std"
]
