[package]
name = "pallet-sylo-data-permissions-rpc-runtime-api"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
codec = { workspace = true }
sp-api = { workspace = true }
sp-std = { workspace = true }
sp-runtime = { workspace = true }

pallet-sylo-data-permissions = { workspace = true }
seed-primitives = { workspace = true }
seed-pallet-common = { workspace = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"pallet-sylo-data-permissions/std",
	"sp-api/std",
	"sp-std/std",
	"seed-primitives/std",
]
