//! Autogenerated weights for `pallet_maintenance_mode`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-09-05, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `Jasons-PC`, CPU: `AMD Ryzen 7 3800X 8-Core Processor`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/seed
// benchmark
// pallet
// --chain
// dev
// --steps=50
// --repeat=20
// --pallet=pallet_maintenance_mode
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output
// ./output

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_nft.
pub trait WeightInfo {
    fn enable_maintenance_mode() -> Weight;
    fn block_account() -> Weight;
    fn block_evm_target() -> Weight;
    fn block_call() -> Weight;
    fn block_pallet() -> Weight;
}

/// Weights for pallet_fee_control using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    // Storage: MaintenanceMode MaintenanceModeActive (r:0 w:1)
    fn enable_maintenance_mode() -> Weight {
        Weight::from_ref_time(16_762_000 as u64)
            .saturating_add(T::DbWeight::get().writes(1 as u64))
    }
    // Storage: MaintenanceMode BlockedAccounts (r:0 w:1)
    fn block_account() -> Weight {
        Weight::from_ref_time(17_763_000 as u64)
            .saturating_add(T::DbWeight::get().writes(1 as u64))
    }
    // Storage: MaintenanceMode BlockedEVMAddresses (r:0 w:1)
    fn block_evm_target() -> Weight {
        Weight::from_ref_time(17_894_000 as u64)
            .saturating_add(T::DbWeight::get().writes(1 as u64))
    }
    // Storage: MaintenanceMode BlockedCalls (r:0 w:1)
    fn block_call() -> Weight {
        Weight::from_ref_time(18_656_000 as u64)
            .saturating_add(T::DbWeight::get().writes(1 as u64))
    }
    // Storage: MaintenanceMode BlockedPallets (r:0 w:1)
    fn block_pallet() -> Weight {
        Weight::from_ref_time(17_984_000 as u64)
            .saturating_add(T::DbWeight::get().writes(1 as u64))
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    // Storage: MaintenanceMode MaintenanceModeActive (r:0 w:1)
    fn enable_maintenance_mode() -> Weight {
        Weight::from_ref_time(16_762_000 as u64)
            .saturating_add(RocksDbWeight::get().writes(1 as u64))
    }
    // Storage: MaintenanceMode BlockedAccounts (r:0 w:1)
    fn block_account() -> Weight {
        Weight::from_ref_time(17_763_000 as u64)
            .saturating_add(RocksDbWeight::get().writes(1 as u64))
    }
    // Storage: MaintenanceMode BlockedEVMAddresses (r:0 w:1)
    fn block_evm_target() -> Weight {
        Weight::from_ref_time(17_894_000 as u64)
            .saturating_add(RocksDbWeight::get().writes(1 as u64))
    }
    // Storage: MaintenanceMode BlockedCalls (r:0 w:1)
    fn block_call() -> Weight {
        Weight::from_ref_time(18_656_000 as u64)
            .saturating_add(RocksDbWeight::get().writes(1 as u64))
    }
    // Storage: MaintenanceMode BlockedPallets (r:0 w:1)
    fn block_pallet() -> Weight {
        Weight::from_ref_time(17_984_000 as u64)
            .saturating_add(RocksDbWeight::get().writes(1 as u64))
    }
}
