// This file is part of Substrate.

// Copyright (C) 2022 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_maintenance_mode
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-09-19, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `ip-172-31-102-147`, CPU: `Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/seed
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=pallet_maintenance_mode
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output
// ./pallet/maintenance-mode/src/weights.rs
// --template
// ./scripts/pallet_template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_maintenance_mode.
pub trait WeightInfo {
	fn enable_maintenance_mode() -> Weight;
	fn block_account() -> Weight;
	fn block_evm_target() -> Weight;
	fn block_call() -> Weight;
	fn block_pallet() -> Weight;
}

/// Weights for pallet_maintenance_mode using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: MaintenanceMode MaintenanceModeActive (r:0 w:1)
	fn enable_maintenance_mode() -> Weight {
		Weight::from_all(37_073_000 as u64)
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: MaintenanceMode BlockedAccounts (r:0 w:1)
	fn block_account() -> Weight {
		Weight::from_all(39_394_000 as u64)
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: MaintenanceMode BlockedEVMAddresses (r:0 w:1)
	fn block_evm_target() -> Weight {
		Weight::from_all(40_700_000 as u64)
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: MaintenanceMode BlockedCalls (r:0 w:1)
	fn block_call() -> Weight {
		Weight::from_all(43_340_000 as u64)
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: MaintenanceMode BlockedPallets (r:0 w:1)
	fn block_pallet() -> Weight {
		Weight::from_all(42_282_000 as u64)
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: MaintenanceMode MaintenanceModeActive (r:0 w:1)
	fn enable_maintenance_mode() -> Weight {
		Weight::from_all(37_073_000 as u64)
			.saturating_add(RocksDbWeight::get().writes(1 as u64))
	}
	// Storage: MaintenanceMode BlockedAccounts (r:0 w:1)
	fn block_account() -> Weight {
		Weight::from_all(39_394_000 as u64)
			.saturating_add(RocksDbWeight::get().writes(1 as u64))
	}
	// Storage: MaintenanceMode BlockedEVMAddresses (r:0 w:1)
	fn block_evm_target() -> Weight {
		Weight::from_all(40_700_000 as u64)
			.saturating_add(RocksDbWeight::get().writes(1 as u64))
	}
	// Storage: MaintenanceMode BlockedCalls (r:0 w:1)
	fn block_call() -> Weight {
		Weight::from_all(43_340_000 as u64)
			.saturating_add(RocksDbWeight::get().writes(1 as u64))
	}
	// Storage: MaintenanceMode BlockedPallets (r:0 w:1)
	fn block_pallet() -> Weight {
		Weight::from_all(42_282_000 as u64)
			.saturating_add(RocksDbWeight::get().writes(1 as u64))
	}
}

