
[package]
name = "pallet-sft-rpc"
version = "2.2.0"
authors = ["The Root Network Team"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
codec = { version = "3.0.0", package = "parity-scale-codec", default-features = false }
jsonrpsee = { version = "0.15.1", features = ["server", "macros"] }

sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v1.0.0" }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v1.0.0" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v1.0.0" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v1.0.0" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v1.0.0" }
sp-rpc = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v1.0.0" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v1.0.0" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v1.0.0" }

pallet-sft = { path = "../" }
pallet-sft-rpc-runtime-api = { path = "./runtime-api" }
seed-primitives = { path = "../../../primitives" }
