
[package]
name = "pallet-sft-rpc"
version = "2.2.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
codec = { workspace = true }
jsonrpsee = { workspace = true }

sp-api = { workspace = true }
sp-arithmetic = { workspace = true }
sp-blockchain = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-rpc = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

pallet-sft = { workspace = true }
pallet-sft-rpc-runtime-api = { workspace = true }
seed-primitives = { workspace = true }
