[package]
name = "precompile-utils-macro"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/tests.rs"

[dependencies]
num_enum = { workspace = true }
proc-macro2 = "1.0"
quote = "1.0"
sha3 = { workspace = true }
syn = { version = "1.0", features = [ "extra-traits", "fold", "full", "visit" ] }

[dev-dependencies]
typenum = { version = "1.17.0", default-features = false }
