[package]
name = "pallet-nfi"
version = "1.0.0"
authors = ["The Root Network Team"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/futureversecom/seed"
description = "Root Network NFI pallet"

[dependencies]

codec = { workspace = true }
scale-info = { workspace = true }
hex-literal = { workspace = true }

sp-core = { workspace = true }
sp-std = { workspace = true }
sp-runtime = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
frame-benchmarking = { workspace = true, optional = true}

pallet-nft = { workspace = true, optional = true }
pallet-sft = { workspace = true, optional = true }
seed-primitives = { workspace = true }
seed-pallet-common = { workspace = true}

[dev-dependencies]
pallet-assets-ext = { workspace = true, default-features = true }
pallet-nft = { workspace = true }
pallet-sft = { workspace = true }
pallet-balances = { workspace = true }
pallet-assets = { workspace = true }
sp-io = { workspace = true }
sp-core = { workspace = true }

[features]
default = ["std"]
std = [
    "codec/std",
    "scale-info/std",
    "seed-primitives/std",
    "seed-pallet-common/std",
    "pallet-nft/std",
    "pallet-sft/std",
    "sp-std/std",
    "sp-runtime/std",
    "frame-support/std",
    "frame-system/std",
    "frame-benchmarking?/std",
]
runtime-benchmarks = ["frame-benchmarking", "pallet-nft/runtime-benchmarks", "pallet-sft/runtime-benchmarks"]
try-runtime = ["frame-support/try-runtime"]