// This file is part of Substrate.

// Copyright (C) 2022 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_token_approvals
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-05-23, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `ip-172-31-102-147`, CPU: `Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/seed
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=pallet-token-approvals
// --extrinsic=*
// --wasm-execution=compiled
// --heap-pages=4096
// --output
// ./pallet/token-approvals/src/weights.rs
// --template
// ./scripts/pallet_template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_token_approvals.
pub trait WeightInfo {
	fn erc721_approval() -> Weight;
	fn erc721_remove_approval() -> Weight;
	fn erc20_approval() -> Weight;
	fn erc20_update_approval() -> Weight;
	fn erc721_approval_for_all() -> Weight;
	fn erc1155_approval_for_all() -> Weight;
}

/// Weights for pallet_token_approvals using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: `Nft::CollectionInfo` (r:1 w:0)
	// Proof: `Nft::CollectionInfo` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	// Storage: `TokenApprovals::ERC721ApprovalsForAll` (r:1 w:0)
	// Proof: `TokenApprovals::ERC721ApprovalsForAll` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	// Storage: `TokenApprovals::ERC721Approvals` (r:0 w:1)
	// Proof: `TokenApprovals::ERC721Approvals` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn erc721_approval() -> Weight {
		Weight::from_all(41_438_000_u64)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Storage: `TokenApprovals::ERC721Approvals` (r:1 w:1)
	// Proof: `TokenApprovals::ERC721Approvals` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	// Storage: `Nft::CollectionInfo` (r:1 w:0)
	// Proof: `Nft::CollectionInfo` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	fn erc721_remove_approval() -> Weight {
		Weight::from_all(41_414_000_u64)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Storage: `TokenApprovals::ERC20Approvals` (r:0 w:1)
	// Proof: `TokenApprovals::ERC20Approvals` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	fn erc20_approval() -> Weight {
		Weight::from_all(16_098_000_u64)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Storage: `TokenApprovals::ERC20Approvals` (r:1 w:1)
	// Proof: `TokenApprovals::ERC20Approvals` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	fn erc20_update_approval() -> Weight {
		Weight::from_all(31_365_000_u64)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Storage: `TokenApprovals::ERC721ApprovalsForAll` (r:0 w:1)
	// Proof: `TokenApprovals::ERC721ApprovalsForAll` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	fn erc721_approval_for_all() -> Weight {
		Weight::from_all(15_913_000_u64)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Storage: `TokenApprovals::ERC1155ApprovalsForAll` (r:0 w:1)
	// Proof: `TokenApprovals::ERC1155ApprovalsForAll` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	fn erc1155_approval_for_all() -> Weight {
		Weight::from_all(16_232_000_u64)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: `Nft::CollectionInfo` (r:1 w:0)
	// Proof: `Nft::CollectionInfo` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	// Storage: `TokenApprovals::ERC721ApprovalsForAll` (r:1 w:0)
	// Proof: `TokenApprovals::ERC721ApprovalsForAll` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	// Storage: `TokenApprovals::ERC721Approvals` (r:0 w:1)
	// Proof: `TokenApprovals::ERC721Approvals` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn erc721_approval() -> Weight {
		Weight::from_all(41_438_000_u64)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	// Storage: `TokenApprovals::ERC721Approvals` (r:1 w:1)
	// Proof: `TokenApprovals::ERC721Approvals` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	// Storage: `Nft::CollectionInfo` (r:1 w:0)
	// Proof: `Nft::CollectionInfo` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	fn erc721_remove_approval() -> Weight {
		Weight::from_all(41_414_000_u64)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	// Storage: `TokenApprovals::ERC20Approvals` (r:0 w:1)
	// Proof: `TokenApprovals::ERC20Approvals` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	fn erc20_approval() -> Weight {
		Weight::from_all(16_098_000_u64)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	// Storage: `TokenApprovals::ERC20Approvals` (r:1 w:1)
	// Proof: `TokenApprovals::ERC20Approvals` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	fn erc20_update_approval() -> Weight {
		Weight::from_all(31_365_000_u64)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	// Storage: `TokenApprovals::ERC721ApprovalsForAll` (r:0 w:1)
	// Proof: `TokenApprovals::ERC721ApprovalsForAll` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	fn erc721_approval_for_all() -> Weight {
		Weight::from_all(15_913_000_u64)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	// Storage: `TokenApprovals::ERC1155ApprovalsForAll` (r:0 w:1)
	// Proof: `TokenApprovals::ERC1155ApprovalsForAll` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	fn erc1155_approval_for_all() -> Weight {
		Weight::from_all(16_232_000_u64)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}

