[package]
name = "pallet-sft"
version = "2.0.1"
description = "Root Network SFT pallet"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
log = { workspace = true }

frame-benchmarking = { workspace = true, optional = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
codec = { workspace = true }
scale-info = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

pallet-nft = { workspace = true }
precompile-utils = { workspace = true }
seed-primitives = { workspace = true }
seed-pallet-common = { workspace = true }

[dev-dependencies]
pallet-assets-ext = { workspace = true, default-features = true }
pallet-balances = { workspace = true }
pallet-assets = { workspace = true }
pallet-evm = { workspace = true }
pallet-timestamp = { workspace = true }

[features]
default = ["std"]
std = [
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"codec/std",
	"scale-info/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"pallet-nft/std",
	"precompile-utils/std",
	"seed-primitives/std",
	"seed-pallet-common/std",
]
runtime-benchmarks = ["frame-benchmarking"]
try-runtime = ["frame-support/try-runtime"]
