[package]
name = "pallet-token-approvals"
version = "2.0.1"
authors = ["The Root Network Team"]
edition = "2021"
repository = "https://github.com/futureversecom/seed"
description = "Seed Token Approvals module"

[dependencies]
seed-primitives = { path = "../../primitives", default-features = false }
seed-pallet-common = { path = "../common", default-features = false }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.145", optional = true, default-features = false }
scale-info = { version = "2.3.0", default-features = false, features = ["derive"] }
pallet-nft = { path = "../nft", default-features = false }

# Substrate
frame-support = { git = "https://github.com/futureversecom/trn-substrate", branch = "polkadot-v0.9.30-warped", default-features = false  }
frame-system = { git = "https://github.com/futureversecom/trn-substrate", branch = "polkadot-v0.9.30-warped", default-features = false  }
frame-benchmarking = { git = "https://github.com/futureversecom/trn-substrate", branch = "polkadot-v0.9.30-warped", default-features = false, optional = true }
sp-std = { git = "https://github.com/futureversecom/trn-substrate", branch = "polkadot-v0.9.30-warped", default-features = false  }
sp-runtime = { git = "https://github.com/futureversecom/trn-substrate", branch = "polkadot-v0.9.30-warped", default-features = false  }
sp-core = { git = "https://github.com/futureversecom/trn-substrate", branch = "polkadot-v0.9.30-warped", default-features = false }

[dev-dependencies]
sp-io = { git = "https://github.com/futureversecom/trn-substrate", branch = "polkadot-v0.9.30-warped" }
hex-literal = { version = "0.3.4" }
pallet-assets-ext = { path = "../assets-ext" }
pallet-balances = { git = "https://github.com/futureversecom/trn-substrate", branch = "polkadot-v0.9.30-warped" }
pallet-assets = { git = "https://github.com/futureversecom/trn-substrate", branch = "polkadot-v0.9.30-warped" }

[features]
default = ["std"]
std = [
    "seed-primitives/std",
    "seed-pallet-common/std",
    "codec/std",
    "serde",
    "sp-runtime/std",
    "sp-std/std",
    "frame-support/std",
    "frame-system/std",
    "scale-info/std",
    "sp-core/std",
    "pallet-nft/std",
]
runtime-benchmarks = ["frame-benchmarking"]
try-runtime = ["frame-support/try-runtime"]