
[package]
name = "pallet-dex-rpc"
version = "0.0.1"
authors = ["The Root Network Team"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
jsonrpsee = { workspace = true }
serde_json = { workspace = true }

sp-api = { workspace = true }
sp-blockchain = { workspace = true }
sp-runtime = { workspace = true }
frame-system = { workspace = true }
sp-core = { workspace = true }

pallet-dex = { workspace = true }
pallet-dex-rpc-runtime-api = { workspace = true }
seed-primitives = { workspace = true }
