
[package]
name = "pallet-dex-rpc"
version = "0.0.1"
authors = ["The Root Network Team"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
jsonrpsee = { version = "0.15.1", features = ["server", "macros"] }

serde_json = "1.0.64"
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.30" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.30" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.30" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.30" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.30" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.30" }

pallet-dex = { path = "../" }
pallet-dex-rpc-runtime-api = { path = "./runtime-api" }
seed-primitives = { path = "../../../primitives" }
