[package]
name = "precompile-utils"
version = "0.1.0"
authors = [ "PureStake", "CENNZnet Developers" ]
edition = "2021"
repository = "https://github.com/futureversecom/parachains"
description = "Utils to write EVM precompiles."

[dependencies]
evm = { git = "https://github.com/rust-blockchain/evm", rev = "01bcbd2205a212c34451d3b4fabc962793b057d3", default-features = false, features = [ "with-codec" ] }
impl-trait-for-tuples = "0.2.2"
log = "0.4"
num_enum = { version = "0.5.3", default-features = false }
sha3 = { version = "0.9", default-features = false }

# Moonbeam
precompile-utils-macro = { path = "macro" }

# Substrate
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
frame-support = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }
frame-system = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }
hex-literal = { version = "*", default-features = false }
rlp = { version = "*", default-features = false }
sp-core = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }
sp-io = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }
sp-std = { git = "https://github.com/futureversecom/substrate", branch = "polkadot-v0.9.23", default-features = false }

# Frontier
fp-evm = { git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.23", default-features = false }
pallet-evm = { git = "https://github.com/futureversecom/frontier", branch = "polkadot-v0.9.23", default-features = false }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"fp-evm/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-evm/std",
	"sp-core/std",
	"sp-io/std",
	"sp-std/std",
]
