name: Porcini Storage Scrap

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: [self-hosted]
    name: Scrap Porcini Storage
    steps:
    - uses: actions/checkout@v3

    - name: Install podman
      run: sudo apt install podman -y

    - name: Create output folder
      run: mkdir -p output

    - name: Build image
      run: podman build -t tchain -f ./dockerimages/rust-1.65.0.Dockerfile .

    - name: Run scraper
      run: podman run --rm -v ./output:/output -t tchain /bin/bash ./ci-scripts/storage-scraper.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: assets-for-download
        path: output
